export enum SectionType {
    CASE_SURVEILLANCE = 'CASE_SURVEILLANCE',
    CONFIRMED_CASES_AND_DEATHS = 'CONFIRMED_CASES_AND_DEATHS',
    TESTS_CUNDUCTED = 'TESTS_CUNDUCTED',
    MAP = 'MAP',
    SUMMARY_TABLE = 'SUMMARY_TABLE',
    SECTION_ONE = 'section1'
}
export enum SectionTitle {
    CASE_SURVEILLANCE = 'CASE SURVEILLANCE AND TESTING',
    CONFIRMED_CASES_AND_DEATHS = 'CONFIRMED CASES AND DEATHS IN LAST 14 DAYS',
    TESTS_CUNDUCTED = 'TESTS CONDUCTED AND POSITIVE CASES IN LAST 14 DAYS',
    MAP = 'GEOGRAPHICAL DISTRIBUTION OF CONFIRMED CASES',
    SUMMARY_TABLE = 'SUMMARY OF SUSPECTS, CONFIRMED AND DEATH CASES BY STATE'
}